# Install Nix, enable magic cache, and install devenv for dev shell.
name: "Setup Nix devenv"
description: "Setup Nix and devenv"
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install devenv
      shell: bash
      run: nix profile install nixpkgs#devenv
